### ISSUE TITLE
no thread safety

### ISSUE THREAD

**Issue by thekant** [joeblau/sample-elevator-control-system#4]
deal with the fact that when multiple people at multiple floors , in front of multiple elevators .. try to add requests .. 

NOTE: synchronize or locked access to adding pickup/requestedFloor for a elevator
           Use TreeSet ..it has methods like ceiling(int value) [returns next greater value]  and floor(int value) [returns next lesser value]

**Comment by joeblau** [comment]
I'm not working on this anymore -- This was just a homework that I was. presented with for a Startup in San Francisco.  I think this is a great systems question, but this was just my answer at the time.  If I as doing this now, I would do a lot of things differently.
